name: CI
permissions:
  contents: write
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: julia --project=. -e 'using Pkg; Pkg.instantiate();'
      - run: julia --project=. make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
